### ISSUE TITLE
check the decoded object: is it complete?

### ISSUE THREAD

**Issue by tmanolat** [raven99p/Grails-Website#45]
https://github.com/raven99p/Grails-Website/blob/730273df16eed6e870b7e7a240ca7172c2b055ed/grails-app/controllers/Authentication/AuthenticationResponderInterceptor.groovy#L28

ok - είδες όχι το cookie είναι valid
τι έχει όμως μέσα;
δεν πρέπει να δεις πχ ότι έχει μέσα ένα username?

όπως είχα πει - αυτό είναι χρήσιμο ώστε να ξέρουμε όχι μονο ότι είναι valid αλλα και ΠΟΙΟΣ χρήστης- ώστε π.χ. αν χρειαζόνταν να κάναμε ειδικά queries για αυτον

**Comment by raven99p** [comment]
ETA  1/4/21
